name: "Proof"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prove:
    name: Prove
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Prove"
        run: |
          docker run -v $PWD/Solers.thy:/home/isabelle/Solers.thy makarius/isabelle:Isabelle2022 process -T Solers
